Verify there's no parser diff

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -35,6 +35,16 @@ jobs:
         working-directory: WebExample
         run: npm ci
 
+      - name: Verify there's no parser diff
+        working-directory: parser
+        run: |
+          npm run build
+          if ! git diff --name-only --exit-code; then
+            # shellcheck disable=SC2016
+            echo 'Error: Parser diff detected! Please run `cd parser && npm run build` and commit the changes.'
+            exit 1
+          fi
+
       - name: Typecheck library
         run: yarn tsc --project tsconfig.json --noEmit
 
