Two spaces instead of four in lint.yml

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -5,35 +5,35 @@ on:
     types: [opened, synchronize]
 
 jobs:
-    lint:
-        runs-on: ubuntu-latest
-        steps:
-            # v5.0.0
-            - name: Check out Git repository
-              uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+      # v5.0.0
+      - name: Check out Git repository
+        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
 
-            # v4.3.0
-            - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
-              with:
-                  path: ~/.yarn
-                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-                  restore-keys: |
-                      ${{ runner.os }}-yarn-
+      # v4.3.0
+      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
+        with:
+          path: ~/.yarn
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+              ${{ runner.os }}-yarn-
 
-            # v6.0.0
-            - name: Setup Node.js
-              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
-              with:
-                node-version-file: '.nvmrc'
+      # v6.0.0
+      - name: Setup Node.js
+        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
+        with:
+          node-version-file: '.nvmrc'
 
-            - name: Install node_modules
-              run: npm ci
+      - name: Install node_modules
+        run: npm ci
 
-            - name: Verify there's no Prettier diff
-              run: |
-                npm run lint -- --fix --quiet
-                if ! git diff --name-only --exit-code; then
-                    # shellcheck disable=SC2016
-                    echo 'Error: Prettier diff detected! Please run `npm run lint -- --fix` and commit the changes.'
-                    exit 1
-                fi
+      - name: Verify there's no Prettier diff
+        run: |
+          npm run lint -- --fix --quiet
+          if ! git diff --name-only --exit-code; then
+              # shellcheck disable=SC2016
+              echo 'Error: Prettier diff detected! Please run `npm run lint -- --fix` and commit the changes.'
+              exit 1
+          fi
